prjNo = input("프로젝트 번호를 입력하세요 : ")
prjTitle = input("프로젝트 제목을 입력하세요 : ")
name = input("이름을 입력하세요 : ")
prjDetail = input("프로젝트 설명을 입력하세요 : ")
inputItem = input("입력해야 하는 데이터의 종류를 입력하세요 : ")
outputCon = input("출력되는 내용을 입력하세요 : ")
usage = input("프로그램 실행 방법을 입력하세요 : ")
date = input("프로그램 작성 일자를 입력하세요 : ")

print("'''")
print("PROJECT", prjNo,".",prjTitle)
print("COPYRIGHT (c) AJOU University")
print("Author   :",name)
print("Details  :",prjDetail)
print("Input    :",inputItem)
print("Output   :",outputCon)
print("Usage    :",usage)
print("History  :",date)
print("'''")
